# Nom du workflow. GitHub affiche les noms de vos workflows sous l’onglet « Actions » de votre référentiel. Si vous omettez name, GitHub affiche le chemin du fichier de workflow relatif à la racine du référentiel.
name: Node.js CI

# Ce workflow assume que la branche par défaut de votre référentiel est `main`. Si la branche par défaut a un nom différent, modifiez cet exemple et ajoutez le nom de la branche par défaut de votre référentiel.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# ... (partie précédente du fichier YAML)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.x', '16.x', '18.x', '20.x']
        redis-version: ['latest']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: npm install
      - run: npm test
